back-end/src/main/java/nl/hu/serious_game/application/HouseService.java
back-end/src/main/java/nl/hu/serious_game/domain/House.java
back-end/src/test/java/nl/hu/serious_game/domain/HouseTest/HouseSolarPanelTest.java

- Domein logica gemaakt voor het toevoegen en verwijderen van zonnepanelen met controle op voorwaardes
- Service methodes aangemaakt voor het toevoegen en verwijderen van zonnepanelen
- Domein tests toegevoegd voor het testen van randvoorwaarden op het domein omtrent zonnepanelen toevoegen en verwijderen

T 101 huis zonnepaneel service

---

back-end/src/main/java/nl/hu/serious_game/Runner.java
back-end/src/main/java/nl/hu/serious_game/SeriousGameApplication.java
back-end/src/main/java/nl/hu/serious_game/application/HouseService.java
back-end/src/main/java/nl/hu/serious_game/domain/Battery.java
back-end/src/main/java/nl/hu/serious_game/domain/House.java
back-end/src/main/java/nl/hu/serious_game/domain/Level.java
back-end/src/main/java/nl/hu/serious_game/domain/Transformer.java
back-end/src/test/java/nl/hu/serious_game/domain/BatteryTest.java
back-end/src/test/java/nl/hu/serious_game/domain/HouseTest/HouseSolarPanelTest.java
back-end/src/test/java/nl/hu/serious_game/domain/TransformerTest.java

- DataSourceAutoConfig excluded zodat de applicatie start zonder datasource configuratie (aangezien wij nu geen db hebben)
- Runner aangemaakt zodat een level aangemaakt kan worden bij het opstarten van de applicatie
- Transformator lijst type veranderd naar List
- Constructor van transformator public gemaakt zodat we er bij kunnen

T 106 level object initialisatie

---

back-end/src/main/java/nl/hu/serious_game/domain/Battery.java
back-end/src/main/java/nl/hu/serious_game/domain/House.java
back-end/src/main/java/nl/hu/serious_game/domain/Level.java
back-end/src/main/java/nl/hu/serious_game/domain/Transformer.java

Clone implementatie toegevoegd en uitgewerkt per klasse die dit nodig heeft om zo het Prototype pattern toe te passen
Verduidelijking: Branch geeft aan dat hier een "Template pattern" implementatie zou komen, maar dit was een misverstand en dit werd een "Prototype pattern"

t 105 clone implementatie (prototype pattern) domein toepassing

---

back-end/.gitignore
front-end/src/components/HelloWorld.vue

basic vue component dat data logt wanneer een button wordt ingedrukt

---

back-end/.gitignore
front-end/src/components/HelloWorld.vue

De code opzet is gemaakt, alleen moet de link worden geupdated met die van de controller. Want die bestaat nog niet.

Connectie code staat er en data wordt gelogd wanneer.

---

back-end/src/main/java/nl/hu/serious_game/domain/Battery.java
back-end/src/main/java/nl/hu/serious_game/domain/House.java
back-end/src/test/java/nl/hu/serious_game/domain/HouseTest/HouseBatteryTest.java

- Tests gemaakt voor het toevoegen van accu's aan een huis en de impact op consumptie/productie
- Battery constructor bereikbaar gemaakt
- Battery attribuut veranderd van list naar enkel object
- Functionaliteit toegevoegd om een batterij toe te voegen aan een huis en de invloed van batterijen opgenomen bij het bepalen van de "current" van een huis
- Extra tests toegevoegd voor het controleren van accu waardes wanneer dit over meerdere uren uitgevoerd wordt

T 132 huis accu functies

---

back-end/src/test/java/nl/hu/serious_game/presentation/AddSolarpanel.json

dit is de json die in de body zou moeten staan bij het toevoegen van zonnepanelen aan een huis.

json dummydata toegevoegd voor toevoegen zonnepanelen

---

back-end/src/main/java/nl/hu/serious_game/Runner.java
back-end/src/main/java/nl/hu/serious_game/domain/Game.java
back-end/src/main/java/nl/hu/serious_game/domain/House.java
back-end/src/main/java/nl/hu/serious_game/domain/Level.java
back-end/src/main/java/nl/hu/serious_game/domain/Transformer.java
back-end/src/main/java/nl/hu/serious_game/domain/exceptions/DoesNotExistException.java
back-end/src/test/java/nl/hu/serious_game/domain/TransformerTest.java

hiermee hoeft de service laag alleen het level object aan te roepen en verder niet alle domein objecten op te halen.

T-129 functies toegevoegd om zonnepanelen en accus toe te voegen via het level object.

---

front-end/package-lock.json
front-end/package.json
front-end/public/LevelDummyData.json
front-end/src/components/Transformer.vue
front-end/src/main.ts
front-end/src/pages/Level.vue
front-end/src/pages/Playground.vue
front-end/src/router/Router.ts

Perongeluk doorgwerkt in deze branch for level-gerelateerde componenten. De omschrijving is daarom even opgesplitst
- Transformator component gemaakt
- Vue router configuratie losgetrokken
- Playground pagina gemaakt voor testen van componenten
Eenvoudige level view gemaakt met 2 kleuren
- Grid aangemaakt voor component plaatsing (voor nu gekozen voor 9x9)
- Dummy data in de public directory gezet voor basic testing
- (Hele) eenvoudige plaatsing logica gemaakt voor transformator en huis componenten
Note: Component "House" in level pagina refereert voor nu naar het transformnator component, omdat huis nog niet af is.
Kleine preview:

T 206 transformer component (en router configuratie + component test mogelijkheid) + T 210, 211, 212

---

front-end/src/components/PopupComponent.vue

PS: vuetify is nog niet toegevoegd in het project bij opzet, dus laten we daar een task van maken

t-209 Popupcomponent aangemaakt die gebruikt kan worden voor transformator en huis. 

---

back-end/src/main/java/nl/hu/serious_game/Runner.java
back-end/src/main/java/nl/hu/serious_game/domain/Congestion.java
back-end/src/main/java/nl/hu/serious_game/domain/House.java
back-end/src/main/java/nl/hu/serious_game/domain/HouseOptions.java
back-end/src/main/java/nl/hu/serious_game/domain/Transformer.java
back-end/src/test/java/nl/hu/serious_game/domain/HouseTest/HouseCongestionTest.java
back-end/src/test/java/nl/hu/serious_game/domain/TransformerTest.java

t-222 Congestie logica implementeren in huis en transformator klas 
en t-223 Congestie logica unit tests maken voor huis en transformator

t-222 en t-223 congestie werkt en is getest

---

back-end/src/main/java/nl/hu/serious_game/application/LevelService.java
back-end/src/main/java/nl/hu/serious_game/config/WebConfig.java
back-end/src/main/java/nl/hu/serious_game/domain/Transformer.java
front-end/package-lock.json
front-end/src/App.vue
front-end/src/components/PopupComponent.vue
front-end/src/pages/Level.vue
front-end/src/utils/api.ts

This pull request includes several changes across both the back-end and front-end components of the application. The most important changes involve modifying the `LevelService` class to use actual IDs instead of indices, adding CORS configuration, updating the `Transformer` class, and enhancing the front-end with new features and dependency updates.
* [`LevelService.java`](diffhunk://#diff-097c225a1fd3ec21706dd19d9b701f56ce088ce97c75a21c45f0980cbb3e088dR37): Updated the `getHouseDTOS` and `runLevel` methods to use actual house and transformer IDs rather than indices. This change improves the accuracy and consistency of ID references. [[1]](diffhunk://#diff-097c225a1fd3ec21706dd19d9b701f56ce088ce97c75a21c45f0980cbb3e088dR37) [[2]](diffhunk://#diff-097c225a1fd3ec21706dd19d9b701f56ce088ce97c7 …

T 247 en T 248 popup voor level (huis)

---

back-end/src/main/java/nl/hu/serious_game/Runner.java
back-end/src/main/java/nl/hu/serious_game/application/LevelService.java
back-end/src/main/java/nl/hu/serious_game/presentation/HTTP-requests.http
back-end/src/main/java/nl/hu/serious_game/presentation/LevelController.java
back-end/src/test/java/nl/hu/serious_game/LevelInitializationTest.java
back-end/src/test/java/nl/hu/serious_game/application/LevelServiceTest.java

Functionaliteit toegevoegd voor het verkijgen van aantal van alle levels. 
Start/update methodes aangepast waar nodig. 
Http req file geupdated.

Aantal levels functionaliteit toegevoegd.

---

front-end/src/utils/api.ts

fetch methode toegevoegd voor het ophalen van de aantal levels vanuit backend

t-273-fetch-aantal-levels

---

front-end/src/pages/LevelSelect.vue

aantal levelselectbuttons worden gegenereerd adhv fetch response. De fetch methode is geïmplementeerd in t-273

t-263-level-selectie-dynamisch

---

front-end/src/pages/Level.vue

This pull request includes several changes to the `front-end/src/pages/Level.vue` file to introduce and process dashboard data. The most important changes include adding a new reactive variable for dashboard data, creating a function to process this data, and integrating the function into existing methods.
Improvements to data handling:
* Added a new reactive variable `dashboardData` to store processed dashboard information.
* Created the `processDashboardData` function to calculate and set values for total energy consumption, green energy production percentage, and other relevant data.
Integration into existing methods:
* Integrated the `processDashboardData` function into the `submitChanges` method to process data after changes are submitted.
* Integrated the `processDashboardData` …

T 262 - Dashboard data beschikbaar gemaakt (en uitbreidbaar gemaakt) voor dashboard implementatie

---

front-end/seriousgamefrontend.code-workspace
front-end/src/App.vue
front-end/src/components/Dashboard.vue
front-end/src/pages/Level.vue
front-end/src/pages/Playground.vue
front-end/src/style.css

prettier is ook weer los gegaan vandaar dat er zoveel lines veranderd zijn

t 260 dashboard component met slots

---

back-end/src/main/java/nl/hu/serious_game/application/LevelService.java
back-end/src/main/java/nl/hu/serious_game/application/dto/out/HouseDTO.java
back-end/src/main/java/nl/hu/serious_game/domain/DayProfile.java
back-end/src/main/java/nl/hu/serious_game/domain/House.java
back-end/src/main/java/nl/hu/serious_game/domain/Transformer.java
front-end/src/components/PopupComponent.vue
front-end/src/pages/Level.vue

This pull request introduces a feature to track and display power costs for houses in the serious game application. The changes include updates to both the back-end and front-end code to support this new feature. The most important changes are outlined below:
* [`LevelService.java`](diffhunk://#diff-097c225a1fd3ec21706dd19d9b701f56ce088ce97c75a21c45f0980cbb3e088dR51-R52): Added methods to get and distribute power costs for houses. (`[[1]](diffhunk://#diff-097c225a1fd3ec21706dd19d9b701f56ce088ce97c75a21c45f0980cbb3e088dR51-R52)`, `[[2]](diffhunk://#diff-097c225a1fd3ec21706dd19d9b701f56ce088ce97c75a21c45f0980cbb3e088dR87)`)
* [`DayProfile.java`](diffhunk://#diff-72c53b8d74f005bd25f0afefba2c2de3303ad64fb85ab654acff396381d08e43R39-R50): Introduced new data for power costs and updated methods …

Kosten per huis toevoeging

---

back-end/src/main/java/nl/hu/serious_game/application/LevelService.java
back-end/src/main/java/nl/hu/serious_game/application/dto/out/LevelDTO.java
back-end/src/main/java/nl/hu/serious_game/domain/Cost.java
back-end/src/main/java/nl/hu/serious_game/domain/Level.java

This pull request introduces several changes to the `LevelService` and `Level` classes to add functionality for checking level completion based on cost and CO2 objectives. Additionally, new methods and properties have been added to the `Cost` and `Level` classes to support these changes.
* [`back-end/src/main/java/nl/hu/serious_game/application/LevelService.java`](diffhunk://#diff-097c225a1fd3ec21706dd19d9b701f56ce088ce97c75a21c45f0980cbb3e088dR76-R78): Added a call to `checkLevelCompletion` in the `updateLevel` method and modified the `runLevel` method to include the `isCompleted` status in the `LevelDTO` return value. Implemented a new private method `checkLevelCompletion` to determine if a level is completed based on cost and CO2 objectives. …

t-293-controle-level-behaald

---

front-end/src/components/ConnectionLine.vue
front-end/src/pages/Level.vue

This pull request includes significant updates to the `ConnectionLine.vue` and `Level.vue` components to enhance the display and interaction of connection lines and their associated information. The changes include adding arrow markers to the lines, refactoring the info box handling, and updating the properties and methods to support the new features.
Enhancements to `ConnectionLine.vue`:
* Added arrow markers to the start and end of the lines based on the `current` and `isProduction` properties.
* Refactored the info box logic to emit events instead of managing it locally within the component.
* Simplified the properties by removing redundant code and updating the `props` section.
Updates to `Level.vue`:
* Integrated the `ConnectionLine` component with the new properties and event …

T 296 connection line direction & Bug fix onMouse event

---

front-end/src/App.vue

This pull request includes changes to the `front-end/src/App.vue` file to enhance the header's visual design and layout. The most important changes involve updating the header background style, adjusting the grid layout, and adding new styles for header elements.
* Updated the header background to a linear gradient for a more modern look.
* Modified the grid layout to include an additional column, improving the alignment of header elements.
* Added styles for the header image and header title, including grid positioning, font size, color, and text alignment.

Header tekst gecentreerd en wat styling geupdate

---

back-end/src/main/java/nl/hu/serious_game/application/LevelService.java
back-end/src/main/java/nl/hu/serious_game/application/dto/out/LevelDTO.java
back-end/src/main/java/nl/hu/serious_game/domain/Level.java
front-end/src/components/Dashboard.vue
front-end/src/components/Notification.vue
front-end/src/pages/Level.vue

This pull request includes significant changes to both the back-end and front-end of the application, focusing on enhancing the `Level` class and updating the dashboard and notification components. The most important changes include adding new properties and methods to the `Level` class, updating the `LevelService` to use these new properties, and modifying the front-end components to display the new data.
* [`back-end/src/main/java/nl/hu/serious_game/domain/Level.java`](diffhunk://#diff-ecde84541429596d567f06f6df6adbd6da7f893194c87d16e24074a896011e6fR16-R17): Added `totalCosts` and `totalCO2` properties along with their getter methods to the `Level` class. Updated `calculateTotalCosts` and `calculateTotalCO2` methods to use these properties. …

t-282 en t-283 zitten beide in deze branch

---

front-end/index.html
front-end/src/components/PopupComponent.vue
front-end/src/pages/Level.vue

This pull request includes significant updates to the `PopupComponent.vue` and `Level.vue` files, focusing on improving the user interface and adding new functionalities. The changes include the addition of new computed properties, restructuring of the popup component layout, and the introduction of cancel functionality.
* [`front-end/index.html`](diffhunk://#diff-325556cc213da244b6a39879649ea66ad5dec658d7ac616075840b524f290b6fR8): Added a link to the Material Design Icons stylesheet to enhance the UI with new icons.
* [`front-end/src/components/PopupComponent.vue`](diffhunk://#diff-7526c0d969ef1241a86be29db843e4c8625e0f0d94a44a6c4ef9eba759c3f955L5-R29): Restructured the popup component layout, including changes to the title section, energy overview section, and buttons for solar panels …

T 307 apply and cancel buttons

---

front-end/src/components/Notification.vue
front-end/src/components/PopupComponent.vue
front-end/src/pages/Level.vue

This pull request includes several changes to the front-end components and pages to improve the user interface and user experience. The most important changes include adding a confetti animation to the `Notification.vue` component, updating the `PopupComponent.vue` for better header alignment and functionality, and enhancing the notification message in `Level.vue`.
Improvements to `Notification.vue`:
* Added a confetti animation that appears when `showConfetti` is true, including the necessary HTML, JavaScript, and CSS. (`front-end/src/components/Notification.vue`) [[1]](diffhunk://#diff-cc1ea78b74ef3e79ca65be4e10845ca2ea152f49e5806440a12fead66cfe141fR15-R17) [[2]](diffhunk://#diff-cc1ea78b74ef3e79ca65be4e10845ca2ea152f49e5806440a12fead66cfe141fR39-R107)
Enhancements to …

Unassigned level fix

---

back-end/src/main/java/nl/hu/serious_game/Runner.java
back-end/src/test/java/nl/hu/serious_game/LevelInitializationTest.java

This pull request introduces several changes to the `Runner.java` file to enhance the level creation process by adding a new level and modifying existing levels' configurations.
Enhancements to level creation:
* Added a new method `createLevel3` to define the parameters and components for the third level, including objectives, houses, and transformers.
* Updated the `createLevels` method to include the newly created `createLevel3` method in the levels list.
Modifications to existing levels:
* Adjusted the objectives, house configurations, and transformer parameters for `createLevel1` and `createLevel2` to balance the level difficulty and gameplay experience. [[1]](diffhunk://#diff-3602d41de05d22d4115e748c0720e90ef709390bf99f32fa39ea97139685c9d9L20-R38) …

t-308 levels aangepast in runner en level 3 aangemaakt

---

back-end/src/main/java/nl/hu/serious_game/application/LevelService.java
back-end/src/main/java/nl/hu/serious_game/application/dto/out/HouseDTO.java
back-end/src/main/java/nl/hu/serious_game/application/dto/out/TransformerDTO.java
back-end/src/main/java/nl/hu/serious_game/domain/House.java
back-end/src/main/java/nl/hu/serious_game/domain/HouseOptions.java
back-end/src/main/java/nl/hu/serious_game/domain/Transformer.java
front-end/src/pages/Level.vue

This pull request introduces limits on the maximum number of solar panels and batteries that can be added to houses and transformers, and ensures these limits are respected in both the back-end and front-end code. The most important changes include adding validation checks, updating DTOs, and modifying the front-end logic to handle these constraints.
Back-end changes:
* [`back-end/src/main/java/nl/hu/serious_game/application/LevelService.java`](diffhunk://#diff-097c225a1fd3ec21706dd19d9b701f56ce088ce97c75a21c45f0980cbb3e088dL107-R108): Added `transformer.getMaxBatteryCount()` to the `runLevel` method to include the maximum battery count in the DTO.
* [`back-end/src/main/java/nl/hu/serious_game/domain/House.java`](diffhunk://#diff-9c4df258e3822324ae43852fbe2c1bef467a2bf4c693b056cacc8191d9e1 …

Us 304 placement limit

---

back-end/src/main/java/nl/hu/serious_game/Runner.java

This pull request introduces a new level to the game by adding `createLevel4` to the `Runner` class in the back-end code. The most important changes include updating the `createLevels` method to include the new level and implementing the `createLevel4` method with its associated logic.
* [`back-end/src/main/java/nl/hu/serious_game/Runner.java`](diffhunk://#diff-3602d41de05d22d4115e748c0720e90ef709390bf99f32fa39ea97139685c9d9L20-R20): Updated the `createLevels` method to include `createLevel4` in the list of levels.
* [`back-end/src/main/java/nl/hu/serious_game/Runner.java`](diffhunk://#diff-3602d41de05d22d4115e748c0720e90ef709390bf99f32fa39ea97139685c9d9R95-R120): Implemented the `createLevel4` method, which includes creating objectives, day profiles, houses, and a transformer for the new …

Level 4 toegevoegd

---

back-end/src/main/java/nl/hu/serious_game/SeedLevelTemplateRunner.java
back-end/src/main/java/nl/hu/serious_game/application/GameLevelService.java
back-end/src/main/java/nl/hu/serious_game/application/LevelTemplateService.java
back-end/src/main/java/nl/hu/serious_game/application/dto/in/GameHouseCreateDTO.java
back-end/src/main/java/nl/hu/serious_game/application/dto/in/LevelHouseCreateDTO.java
back-end/src/main/java/nl/hu/serious_game/application/dto/in/LevelHouseUpdateDTO.java
back-end/src/main/java/nl/hu/serious_game/application/dto/in/LevelTemplateCreateDTO.java
back-end/src/main/java/nl/hu/serious_game/application/dto/out/LevelTemplateDTO.java
back-end/src/main/java/nl/hu/serious_game/domain/GameLevel.java
back-end/src/main/java/nl/hu/serious_game/domain/LevelTemplate.java
back-end/src/main/java/nl/hu/serious_game/presentation/HTTP-requests.http
back-end/src/test/java/nl/hu/serious_game/GameLevelInitializationTest.java
back-end/src/test/java/nl/hu/serious_game/application/GameLevelServiceTest.java
back-end/src/test/java/nl/hu/serious_game/domain/GameLevelTest.java

moved costs property to LevelTemplate from GameLevel

---

front-end/src/app.css
front-end/src/pages/LoginPage.vue
front-end/src/pages/RegisterPage.vue

Built register and login page, incl. app.css hover effect color

---

back-end/HTTP-requests.http
back-end/src/main/java/nl/hu/serious_game/domain/LevelTemplate.java
back-end/src/main/java/nl/hu/serious_game/presentation/LevelTemplateController.java
front-end/src/components/level-editor/LevelEditor.vue

Fix bug in backend wanneer endTime = 24

---

back-end/src/main/java/nl/hu/serious_game/domain/LevelTemplate.java
back-end/src/main/java/nl/hu/serious_game/domain/LevelType.java
back-end/src/main/java/nl/hu/serious_game/domain/Race.java
back-end/src/main/java/nl/hu/serious_game/presentation/RaceController.java
back-end/src/test/java/nl/hu/serious_game/application/GameLevelServiceTest.java

Backend entities for races

---

front-end/src/components/global/level-editor/LevelEditor.vue

Knop en input naast de huizen knop gedaan, en het informatie ding toegevoegd

---

ai-back-end/.gitignore
ai-back-end/requirements.txt
ai-back-end/src/chatbot.py

ik heb for the time being het model van die website erin gezet, ik wil dit nog bespreken met Joost. Als ik dit niet doe kan ik vrij lastig verder met de rest van het back-end gedeelte :(.

Model van Nebius AI studio werkend
